base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from core.views.base import BaseIndexTemplate

from . import urls_api

schema_view = get_schema_view(
    openapi.Info(
        title="E-Collect API",
        default_version="v1",
        description="Swagger do Projeto E-Collect API",
        terms_of_service="https://www.rede.ulbra.br/",
        contact=openapi.Contact(email="marcomartins06@rede.ulbra.br"),
        license=openapi.License(name="BSD License"),
    ),
    url="http://127.0.0.1:8000" if settings.DEBUG else "https://www.rede.ulbra.br",
    public=True,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", BaseIndexTemplate.as_view(), name="index"),
    path("core/", include("core.urls", namespace="core")),
    path("core/", include("usuario.urls", namespace="usuario")),
    path("core/", include("configuracao_agtec_core.urls", namespace="configuracao_agtec_core")),
    # Urls do Swagger
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    # Url de autenticação do DRF
    path("auth/", include("dj_rest_auth.urls")),
    # URL de autenticação JWT
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]

# Adicionando as urls da APIRest no urlpatterns do projeto
urlpatterns += urls_api.urlpatterns

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

usuario/urls.py
from django.urls import path

from .views import (
    UsuarioCreateView,
    UsuarioDeleteView,
    UsuarioDetailView,
    UsuarioIndexTemplateView,
    UsuarioListView,
    UsuarioLoginView,
    UsuarioLogoutView,
    UsuarioProfileView,
    UsuarioRestoreView,
    UsuarioUpdateView,
)

app_name = "usuario"

# URLs do Models Usuario
urlpatterns = [
    path("login/", UsuarioLoginView.as_view(), name="login"),
    path("userlogout/", UsuarioLogoutView.as_view(), name="logout"),
    path("userprofile/", UsuarioProfileView.as_view(), name="profile"),
]


# URLs do Models Usuario
urlpatterns += [
    path("usuario/", UsuarioIndexTemplateView.as_view(), name="usuario-index"),
    path("usuario/usuario/", UsuarioListView.as_view(), name="usuario-list"),
    path("usuario/usuario/create/", UsuarioCreateView.as_view(), name="usuario-create"),
    path("usuario/usuario/<uuid:pk>/", UsuarioDetailView.as_view(), name="usuario-detail"),
    path("usuario/usuario/update/<uuid:pk>/", UsuarioUpdateView.as_view(), name="usuario-update"),
    path("usuario/usuario/delete/<uuid:pk>/", UsuarioDeleteView.as_view(), name="usuario-delete"),
    path("usuario/usuario/restore/<uuid:pk>/", UsuarioRestoreView.as_view(), name="usuario-restore"),
]

core/management/commands/snippets/fastapi_project/usuario/models.py
import sqlalchemy as sa
from authentication.models import User
from sqlalchemy.orm import Mapped, mapped_column

from core.database import Base


class Usuario(Base):
    __tablename__ = "usuario_usuario"

    django_user_id: Mapped[int] = mapped_column(sa.ForeignKey(User.id), nullable=False)
    cpf: Mapped[str] = mapped_column(sa.String(11), nullable=True)
    nome: Mapped[str] = mapped_column(sa.String(300), nullable=False)
    email: Mapped[str] = mapped_column(sa.String(254), nullable=False)
    telefone: Mapped[str] = mapped_column(sa.String(100), nullable=True)
    token: Mapped[str] = mapped_column(sa.String, nullable=True)
    firebase: Mapped[str] = mapped_column(sa.String, nullable=True)
    access_token: Mapped[str] = mapped_column(sa.String, nullable=True)
    id_token: Mapped[str] = mapped_column(sa.String, nullable=True)
    latitude: Mapped[float] = mapped_column(sa.Float, nullable=False, default=0.0)
    longitude: Mapped[float] = mapped_column(sa.Float, nullable=False, default=0.0)
    endereco: Mapped[str] = mapped_column(sa.String, nullable=True)

usuario/models.py
from django.contrib.auth.models import User
from django.db import models

from core.models import Base


class Usuario(Base):
    """Classe padrão para gerenciamento de todos os usuários da plataforma"""

    django_user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        verbose_name="Django User",
    )
    cpf = models.CharField("CPF", max_length=11, blank=True, null=True, unique=True)
    nome = models.CharField("Nome", max_length=300)
    email = models.EmailField("E-mail", unique=True)
    telefone = models.CharField("Telefone", max_length=100, blank=True, null=True)
    token = models.TextField("Token", blank=True, null=True, editable=False)
    firebase = models.TextField("Token Firebase", blank=True, null=True)
    access_token = models.TextField("Access Token", blank=True, null=True)
    id_token = models.TextField("ID Token", blank=True, null=True)
    latitude = models.FloatField("Latitude", default=0.0)
    longitude = models.FloatField("Longitude", default=0.0)
    endereco = models.TextField("Endereço Residencial", blank=True, null=True)

    @staticmethod
    def get_display_username(django_user):
        """
        Método responsável por retornar o atributo do usuário logado
        que será utilizado no template header_menu.html
        """
        if django_user.is_authenticated:
            if usuario := Usuario.objects.filter(django_user=django_user).first():
                return f"{usuario.nome} (Admin)" if django_user.is_superuser else usuario.nome
            elif django_user.is_superuser:
                return f"{django_user.first_name or django_user.username} (Admin)"
            return django_user.first_name or django_user.username
        return "Visitante"

    class Meta:
        verbose_name = "Usuário"
        verbose_name_plural = "Usuários"
        fields_display = ["nome", "email", "telefone", "endereco"]
        icon_model = "fas fa-user"

    def save(self, *args, **kwargs):
        # Checa se o email foi alterado
        # para modificar o Django User no Signal
        if not self._state.adding:
            old = Usuario.objects.get(pk=self.pk)
            if old.email != self.email:
                old.django_user.is_active = False
                old.django_user.save()
                self.django_user = None
                self.token = None
        super().save(*args, **kwargs)

    def __str__(self):
        return f"Usuario: {self.cpf} | {self.email}"

usuario/forms.py
from core.forms import BaseForm

from .models import Usuario


class UsuarioForm(BaseForm):
    """Form padrão para o model Usuario"""

    class Meta:
        exclude = ["deleted", "enabled"]
        model = Usuario

usuario/views/index.py
from core.views.base import BaseTemplateView


# Views Inicial Usuario
class UsuarioIndexTemplateView(BaseTemplateView):
    # Views para renderizar a tela inicial Usuario
    template_name = "usuario/index.html"
    context_object_name = "usuario"

    def get_context_data(self, **kwargs):
        context = super(UsuarioIndexTemplateView, self).get_context_data(**kwargs)
        return context

usuario/views/usuario.py
from django.contrib.auth.views import LoginView, LogoutView

from base.settings import SYSTEM_NAME
from configuracao_agtec_core.models import ImagemLogin, LogoSistema
from core.views.base import (
    BaseCreateView,
    BaseDeleteView,
    BaseDetailView,
    BaseListView,
    BaseRestoreView,
    BaseTemplateView,
    BaseUpdateView,
)
from usuario.forms import UsuarioForm
from usuario.models import Usuario

# Views Inicial Usuario


class UsuarioLoginView(LoginView):
    # Views para renderizar a tela inicial Usuario
    template_name = "usuario/registration/login.html"
    context_object_name = "usuario"

    def get_context_data(self, **kwargs):
        """
        The get_context_data function is a method that Django calls when rendering the template.
        It allows you to add additional context variables to the template, which are then available in
        the rendered HTML. In this case, we're adding two new variables: background and logo.

        Parameters
        ----------
            self
                Represent the instance of the object
            **kwargs
                Pass keyworded, variable-length argument list

        Returns
        -------

            The context of the view

        Doc Author
        ----------
            Trelent
        """
        context = super(UsuarioLoginView, self).get_context_data(**kwargs)
        context["background"] = ImagemLogin.objects.filter(ativo=True, login_usuario=True).order_by("?").first()
        context["logo"] = LogoSistema.objects.filter(ativo=True).order_by("?").first()
        context["system_name"] = SYSTEM_NAME
        return context


class UsuarioLogoutView(LogoutView):
    template_name = "usuario/registration/login.html"


class UsuarioProfileView(BaseTemplateView):
    template_name = "usuario/registration/profile.html"


# Fim das Views do Models Usuario


# Views do Models Usuario
class UsuarioListView(BaseListView):
    """Classe para gerenciar a listagem do Usuario"""

    model = Usuario
    template_name = "usuario/usuario/usuario_list.html"
    context_object_name = "usuario"
    list_display = ["nome", "email", "telefone", "endereco"]
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(UsuarioListView, self).get_context_data(**kwargs)
        return context

    def get_queryset(self):
        """Subscrevendo o queryset para
        filtrar os dados conforme o perfil logado

        Returns:
            QuerySet
        """

        if self.request.user.is_superuser:
            queryset = super(UsuarioListView, self).get_queryset()
            return queryset
        else:
            queryset = super(UsuarioListView, self).get_queryset()
            return queryset


class UsuarioDetailView(BaseDetailView):
    """Classe para gerenciar o detalhe do Usuario"""

    model = Usuario
    form_class = UsuarioForm
    success_url = "usuario:usuario-list"
    template_name = "usuario/usuario/usuario_detail.html"
    context_object_name = "usuario"

    def get_context_data(self, **kwargs):
        context = super(UsuarioDetailView, self).get_context_data(**kwargs)
        return context


class UsuarioCreateView(BaseCreateView):
    """Classe para gerenciar o create do Usuario"""

    model = Usuario
    form_class = UsuarioForm
    context_object_name = "usuario"
    success_url = "usuario:usuario-list"
    template_name = "usuario/usuario/usuario_create.html"
    # inlines = []


class UsuarioUpdateView(BaseUpdateView):
    """Classe para gerenciar a update do Usuario"""

    model = Usuario
    form_class = UsuarioForm
    context_object_name = "usuario"
    success_url = "usuario:usuario-list"
    template_name = "usuario/usuario/usuario_update.html"
    # inlines = []


class UsuarioDeleteView(BaseDeleteView):
    """Classe para gerenciar o delete do Usuario"""

    model = Usuario
    form_class = UsuarioForm
    context_object_name = "usuario"
    success_url = "usuario:usuario-list"
    template_name = "usuario/usuario/usuario_delete.html"


class UsuarioRestoreView(BaseRestoreView):
    """Classe para gerenciar o restore do Usuario"""

    model = Usuario
    context_object_name = "usuario"
    success_url = "usuario:usuario-list"
    template_name = "usuario/usuario/usuario_restore.html"


# Fim das Views do Models Usuario

usuario/templates/usuario/usuario/usuario_delete.html
<!--
Arquivo gerado automaticamente pelo build.
Caso deseje bloquear o parser nesse arquivo, basta adicionar o caracter #(cerquilha) antes da palavra a seguir
#FileLocked
-->
{% extends "core/index_delete.html" %}
{% load base %}
{% block title %}
    Deletar Usuário
{% endblock title %}
{% block title_modulo %}
    Usuário
{% endblock title_modulo %}
{% block titledelete_app %}
    <h3 class="m-4">Apagar: {{ object }} ?</h3>
{% endblock titledelete_app %}
{% block delete_app %}
    <form class="needs-validation was-validated flex-buttons-end gap-small"
          method="post"
          novalidate>
        {% csrf_token %}
        <div>
            <a href="{% url 'usuario:usuario-list' %}" class="br-button block">Cancelar</a>
        </div>
        <div>
            <input type="submit" class="br-button danger block" value="Excluir" />
        </div>
    </form>
{% endblock delete_app %}

usuario/templates/usuario/usuario/usuario_detail.html
{% extends "core/index_detail.html" %}
{% load static %}
{% load base %}
<!--
Arquivo gerado automaticamente pelo build.
Caso deseje bloquear o parser nesse arquivo, basta adicionar o caracter #(cerquilha) antes da palavra a seguir
#FileLocked
-->
{% block title %}
    Detalhes de Usuário
{% endblock title %}
<span class="text-muted font-weight-light"></span>
{% block title_modulo %}
    <h4 class="font-weight-bold py-3 mb-4">
        <span class="text-muted font-weight-light">Usuário /</span> Detalhes {{ model_name }}
    </h4>
{% endblock title_modulo %}
<div class="row">
    {% block menu_app %}
        {% for app in apps %}
            {% if app.real_name_app.lower == 'usuario' %}
                {% for model in app.models_app %}
                    {% if model|has_view_permission:request %}
                        <div class="col-xl-12">
                            <i class="ion ion-md-arrow-dropight text-muted"></i> &nbsp;
                            <a href="{% url model.path_url %}">{{ model.name_model|title }}</a>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endfor %}
    {% endblock menu_app %}
    {% block detail %}
        <div class="col-xl-12">
            <div class="br-list" role="list">
                {% for field in object_list %}
                    <div class="col-xl-6">
                        <h4 class="align-items-center my-4">{{ field.0|capfirst }}</h4>
                        <p>{{ field.1 }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="card-footer flex-buttons-end gap-small">
            <div>
                <a class="br-button block" href="{% url 'usuario:usuario-list' %}">Voltar</a>
            </div>
            {% if perms.core.view_audit and audit %}
                <div>
                    <a href="{% url url_detail object.pk %}audit"
                       class="br-button secondary block">Auditar</a>
                </div>
            {% endif %}
        </div>
    {% endblock detail %}
</div>

usuario/templates/usuario/usuario/usuario_list.html
<!--
Arquivo gerado automaticamente pelo build.
Caso deseje bloquear o parser nesse arquivo, basta adicionar o caracter #(cerquilha) antes da palavra a seguir
FileLocked
-->
{% extends "core/index_list.html" %}
{% load base %}
{% block title %}
    Listagem Usuário
{% endblock title %}
{% block title_modulo %}
    <h4 class="font-weight-bold m-1">Usuário - {{ model_name }}</h4>
{% endblock title_modulo %}
<!-- Bloco para passagem da URL do formulário de cadastro -->
{% block uriadd %}
    {% url "usuario:usuario-create" %}
{% endblock uriadd %}
{% block list_app %}
    <table>
        <thead>
            <tr>
                <th class="table-actions" scope="col">Ações</th>
                <th></th>
                <!--REPLACE_THEAD-->
                <th scope="col" class="table-delete"></th>
            </tr>
        </thead>
        <tbody>
            {% for item in usuario %}
                <tr {% if item.deleted %}class="deleted"{% endif %}>
                    <td class="text-center">
                        {% if perms.usuario.view_usuario %}
                            <a href="{% url 'usuario:usuario-detail' item.pk %}"
                               class="br-button circle primary small m-1"
                               data-toggle="tooltip"
                               data-placement="bottom"
                               title="Visualizar">
                                <i class="fas fa-eye fa-sm"></i>
                            </a>
                        {% endif %}
                        {% if perms.usuario.change_usuario %}
                            <a href="{% url 'usuario:usuario-update' item.pk %}"
                               class="br-button secondary circle small m-1"
                               data-toggle="tooltip"
                               data-placement="bottom"
                               title="Editar">
                                <i class="fas fa-pencil-alt fa-sm"></i>
                            </a>
                        {% endif %}
                    </td>
                    <td></td>
                    <!--REPLACE_TLINE-->
                    <td class="text-center">
                        {% if perms.usuario.delete_usuario %}
                            {% if item.deleted %}
                                <a href="{% url 'usuario:usuario-restore' item.pk %}"
                                   class="br-button circle small text-success"
                                   data-toggle="tooltip"
                                   data-placement="bottom"
                                   title="Restaurar">
                                    <i class="fas fa-trash-restore fa-sm"></i>
                                </a>
                            {% else %}
                                <a href="{% url 'usuario:usuario-delete' item.pk %}"
                                   class="br-button circle small text-danger"
                                   data-toggle="tooltip"
                                   data-placement="bottom"
                                   title="Excluir">
                                    <i class="fas fa-trash fa-sm"></i>
                                </a>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock list_app %}
{% block size_itens %}
    Exibindo {{ usuario.count }} de {{ paginator.count }} itens encontrados.
{% endblock size_itens %}

usuario/templates/usuario/usuario/usuario_restore.html
<!--
Arquivo gerado automaticamente pelo build.
Caso deseje bloquear o parser nesse arquivo, basta adicionar o caracter #(cerquilha) antes da palavra a seguir
#FileLocked
-->
{% extends "core/index_restore.html" %}
{% load base %}
{% block title %}
    Restaurar Usuário
{% endblock title %}
{% block title_modulo %}
    Usuário
{% endblock title_modulo %}
{% block titlerestore_app %}
    <h3 class="m-4">Restaurar: {{ object }} ?</h3>
{% endblock titlerestore_app %}
{% block restore_app %}
    <form class="needs-validation was-validated flex-buttons-end gap-small"
          method="post"
          novalidate>
        {% csrf_token %}
        <div>
            <a href="{% url 'usuario:usuario-list' %}" class="br-button block">Cancelar</a>
        </div>
        <div>
            <input type="submit" class="br-button block primary" value="Restaurar">
        </div>
    </form>
{% endblock restore_app %}