base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from core.views.base import BaseIndexTemplate

from . import urls_api

schema_view = get_schema_view(
    openapi.Info(
        title="E-Collect API",
        default_version="v1",
        description="Swagger do Projeto E-Collect API",
        terms_of_service="https://www.rede.ulbra.br/",
        contact=openapi.Contact(email="marcomartins06@rede.ulbra.br"),
        license=openapi.License(name="BSD License"),
    ),
    url="http://127.0.0.1:8000" if settings.DEBUG else "https://www.rede.ulbra.br",
    public=True,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", BaseIndexTemplate.as_view(), name="index"),
    path("core/", include("core.urls", namespace="core")),
    path("core/", include("usuario.urls", namespace="usuario")),
    path("core/", include("configuracao_agtec_core.urls", namespace="configuracao_agtec_core")),
    # Urls do Swagger
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    # Url de autenticação do DRF
    path("auth/", include("dj_rest_auth.urls")),
    # URL de autenticação JWT
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]

# Adicionando as urls da APIRest no urlpatterns do projeto
urlpatterns += urls_api.urlpatterns

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

core/urls.py
from core.views.audit import (
    AuditDetailView,
    AuditListView,
    AuditObjectListView,
    AuditTemplateView,
)
from core.views.auth import LoginView, LogoutView, ResetPassword, UpdatePassword
from core.views.misc import (
    IndexAdminTemplateView,
    ProfileUpdateView,
    ProfileView,
    SettingsView,
)
from django.urls import path

app_name = "core"
urlpatterns = [
    path("", IndexAdminTemplateView.as_view(), name="index"),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("profile/", ProfileView.as_view(), name="profile"),
    path("profile/update/", ProfileUpdateView.as_view(), name="profile-update"),
    path("profile/reset/password/", ResetPassword.as_view(), name="reset-password"),
    path("profile/update/password/", UpdatePassword.as_view(), name="password-update"),
    path("settings/", SettingsView.as_view(), name="settings"),
]

# Auditoria
urlpatterns += [
    path("audit/", AuditTemplateView.as_view(), name="audit-index"),
    path("audit/audit/", AuditListView.as_view(), name="audit-list"),
    path("audit/<int:pk>/", AuditDetailView.as_view(), name="audit-detail"),
    path(
        "<path:object_id>/<int:pk>/audit/",
        AuditListView.as_view(),
        name="audit-detail_model-list",
    ),
    path(
        "<path:object_id>/audit/",
        AuditObjectListView.as_view(),
        name="audit-list_model-list",
    ),
    path(
        "<path:object_id>/audit/<int:pk>/",
        AuditDetailView.as_view(),
        name="audit-list_model-detail",
    ),
    path(
        "<path:object_id>/<int:id>/audit/<int:pk>/",
        AuditDetailView.as_view(),
        name="audit-detail_model-detail",
    ),
]

core/management/commands/snippets/fastapi_project/authentication/models.py
import datetime

import sqlalchemy as sa
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column, relationship

"""
Arquivo com os  models da app de autenticação

- É configurado o nome da tabela, colunas e relacionamentos
"""


class Base(DeclarativeBase):
    __abstract__ = True


class ContentType(Base):
    __tablename__ = "django_content_type"

    id: Mapped[int] = mapped_column(sa.Integer, primary_key=True, index=True)
    app_label: Mapped[str] = mapped_column(sa.String, nullable=False)
    model: Mapped[str] = mapped_column(sa.String, nullable=False)


class Permission(Base):
    __tablename__ = "auth_permission"

    id: Mapped[int] = mapped_column(sa.Integer, primary_key=True, index=True)
    name: Mapped[str] = mapped_column(sa.String, nullable=False)
    content_type_id: Mapped[int] = mapped_column(
        sa.ForeignKey("django_content_type.id"), nullable=False
    )
    codename: Mapped[str] = mapped_column(sa.String, nullable=False)
    contentType = relationship("ContentType")


group_permission = sa.Table(
    "auth_group_permissions",
    Base.metadata,
    sa.Column("group_id", sa.ForeignKey("auth_group.id"), primary_key=True),
    sa.Column("permission_id", sa.ForeignKey("auth_permission.id"), primary_key=True),
)


class Group(Base):
    __tablename__ = "auth_group"

    id: Mapped[int] = mapped_column(sa.Integer, primary_key=True, index=True)
    name: Mapped[str] = mapped_column(sa.String, nullable=False)
    permissions = relationship("Permission", secondary=group_permission)


user_group = sa.Table(
    "auth_user_groups",
    Base.metadata,
    sa.Column("group_id", sa.ForeignKey("auth_group.id"), primary_key=True),
    sa.Column("user_id", sa.ForeignKey("auth_user.id"), primary_key=True),
)


class User(Base):
    __tablename__ = "auth_user"

    id: Mapped[int] = mapped_column(sa.Integer, primary_key=True, index=True)
    first_name: Mapped[str] = mapped_column(sa.String)
    last_name: Mapped[str] = mapped_column(sa.String)
    username: Mapped[str] = mapped_column(sa.String, nullable=False)
    email: Mapped[str] = mapped_column(sa.String, unique=True, index=True)
    password: Mapped[str] = mapped_column(sa.String, nullable=False)
    is_active: Mapped[bool] = mapped_column(sa.Boolean, default=True)
    is_superuser: Mapped[bool] = mapped_column(sa.Boolean, default=False)
    groups = relationship("Group", secondary=user_group)
    is_staff = mapped_column(sa.Boolean, default=False)
    date_joined = mapped_column(sa.DateTime, default=datetime.datetime.now)

core/management/commands/snippets/fastapi_project/usuario/models.py
import sqlalchemy as sa
from authentication.models import User
from sqlalchemy.orm import Mapped, mapped_column

from core.database import Base


class Usuario(Base):
    __tablename__ = "usuario_usuario"

    django_user_id: Mapped[int] = mapped_column(sa.ForeignKey(User.id), nullable=False)
    cpf: Mapped[str] = mapped_column(sa.String(11), nullable=True)
    nome: Mapped[str] = mapped_column(sa.String(300), nullable=False)
    email: Mapped[str] = mapped_column(sa.String(254), nullable=False)
    telefone: Mapped[str] = mapped_column(sa.String(100), nullable=True)
    token: Mapped[str] = mapped_column(sa.String, nullable=True)
    firebase: Mapped[str] = mapped_column(sa.String, nullable=True)
    access_token: Mapped[str] = mapped_column(sa.String, nullable=True)
    id_token: Mapped[str] = mapped_column(sa.String, nullable=True)
    latitude: Mapped[float] = mapped_column(sa.Float, nullable=False, default=0.0)
    longitude: Mapped[float] = mapped_column(sa.Float, nullable=False, default=0.0)
    endereco: Mapped[str] = mapped_column(sa.String, nullable=True)

core/forms.py
from django import forms
from django.forms.fields import BooleanField, DateField, DateTimeField, JSONField
from django.utils.translation import gettext_lazy as _

from .models import Audit, Base


class BaseForm(forms.ModelForm):
    """Form para ser usado no classe based views"""

    # Sobrescrevendo o Init para aplicar as regras CSS
    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop("request", None)
        super(BaseForm, self).__init__(*args, **kwargs)

        for field in iter(self.fields):
            # Coleta as classes passadas no Form
            class_attrs = self.fields[field].widget.attrs.get("class", "")

            # Aplica o padrão
            class_attrs += " form-control"

            # Verificando se o campo está configurado como obrigatório
            if self.fields[field].required:
                class_attrs += " obrigatorio"

            # Verificando se o campo é Booleano
            if isinstance(self.fields[field], BooleanField):
                class_attrs += " checked-left"

            # Verificando se o campo é do tipo DateTime
            if isinstance(self.fields[field], DateTimeField):
                class_attrs += " datetimefield"
                self.fields[field].widget.attrs.update({"placeholder": "dd/mm/aaaa hh:mm"})

            # Verificando se o campo é do tipo Date
            if isinstance(self.fields[field], DateField):
                class_attrs += " datefield"
                self.fields[field].widget.attrs.update({"placeholder": "dd/mm/aaaa"})

            # # Verificando se o campo é do tipo FileField
            # if isinstance(self.fields[field], FileField):
            #     class_attrs += " custom-file-input"

            # # Verificando se o campo é do tipo ImageField
            # if isinstance(self.fields[field], ImageField):
            #     class_attrs += " custom-file-input"

            # # Verificando se o campo é do tipo BooleanField
            if isinstance(self.fields[field], BooleanField):
                class_attrs += " form-check-input"

            # Atualizando os atributos do campo para adicionar as classes
            # conforme as regras anteriores
            self.fields[field].widget.attrs.update({"class": class_attrs.lstrip()})

    class Meta:
        model = Base
        exclude = ["enabled", "deleted"]


"""
=========================================================================
=========================================================================
=========================================================================
=========================================================================
=========================================================================
=========================================================================
                    Área dos models de Auditoria
=========================================================================
=========================================================================
=========================================================================
=========================================================================
=========================================================================
=========================================================================
"""


class AuditForm(forms.ModelForm):
    previous_data_change = JSONField(help_text=_("before the time of the change"))
    current_data = JSONField(help_text=_("data at the time of the change"))
    user_change = JSONField(label=_("user"), help_text=_("user who changed the data"))
    user_permissions_change = JSONField(label=_("user permissions"), help_text=_("permissions at the time of change"))
    user_groups_change = JSONField(label=_("user groups"), help_text=_("groups at the time of change"))

    class Meta:
        fields = "__all__"
        model = Audit

core/views/constants.py
# Apps e Models que devem ser ignorados ao renderizar o menu Core
IGNORED_APPS = [
    "debug_toolbar",
    "dj_rest_auth",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_extensions",
    "drf_yasg",
    "rest_framework",
    "rest_framework.authtoken",
    "tempus_dominus",
]

IGNORED_MODELS = [
    "parameterforbase",
]

core/views/utils.py
import logging
from uuid import UUID

from base.settings import IGNORED_APPS as IGNORED_APPS_BASE
from core.views.constants import IGNORED_APPS, IGNORED_MODELS
from django.contrib.contenttypes.models import ContentType
from django.utils.text import camel_case_to_spaces

# Configurando o logger
logger = logging.getLogger(__name__)


def has_fk_attr(classe=None, attr=None):
    try:
        classe.objects.values(attr)

    except Exception:
        return False

    return True


def get_breadcrumbs(url_str):
    """
    Método para criar o Breadcrumbs a ser utilizado nos templastes
    Arguments:
        url_str {String} -- [Nome da app e do Models]
    Returns:
        [Lista] -- [Lista com o breadcrumb]
    """

    breadcrumbs = [
        {
            "slug": "Inicio",
            "url": "/",
        }
    ]
    url = "/"

    array_url = url_str.strip("/").split("/")
    for cont, slug in enumerate(array_url, start=1):
        breadcrumb = {}

        if slug != "":
            if isinstance(slug, UUID):
                breadcrumb["slug"] = ContentType.objects.get(
                    app_label=array_url[1], model=array_url[2]
                ).model_class().objects.get(pk=slug)

            else:
                breadcrumb["slug"] = camel_case_to_spaces(slug).title()

            if cont < len(array_url):
                url = f"{url}{slug.lower()}/"
                breadcrumb["url"] = url

            breadcrumbs.append(breadcrumb)

    return breadcrumbs


def get_apps():
    """Método para recuperar todas as apps

    Returns:
        List -- Lista com as apps que o usuário tem acesso
    """

    from django.apps import apps

    _apps = []
    for app in apps.get_app_configs():

        try:
            if app.name in IGNORED_APPS or app.name in IGNORED_APPS_BASE:
                continue

            _models = []
            app_models = sorted(app.get_models(), key=lambda x: x._meta.verbose_name)
            for model in app_models:
                if model._meta.model_name in IGNORED_MODELS:
                    continue

                __model_icon = (
                    model._meta.icon_model
                    if hasattr(model._meta, "icon_model")
                    else "fas fa-angle-right"
                )

                _models.append(
                    {
                        "name_model": model._meta.verbose_name,
                        "url_list_model": "/{app}/{model}/".format(
                            app=model._meta.app_label, model=model._meta.model_name
                        ),
                        "path_url": "{app}:{model}-list".format(
                            app=model._meta.app_label.lower(),
                            model=model._meta.model_name.lower(),
                        ),
                        "real_name_model": model._meta.model_name,
                        "icon_model": __model_icon,
                    }
                )

            if _models:
                icon = app.icon if hasattr(app, "icon") else "fas fa-align-justify"

            _apps.append(
                {
                    "name_app": f"{app.verbose_name}",
                    "icon_app": icon,
                    "models_app": _models,
                    "index_url_app": f"{model._meta.app_label}:{model._meta.app_label}-index",
                    "real_name_app": app.name,
                    "real_name_model": model._meta.model_name,
                }
            )

        except Exception as error:
            print(error)
            continue

    return sorted(_apps, key=lambda x: x["name_app"])

core/templates/core/base.html
{% load static %}
{% load base %}
<!DOCTYPE html>
<html lang="pt-br" class="default-style">
      <head>
            <title>
                  {% block title %}
                  {% endblock title %}
            </title>
            <meta charset="utf-8"/>
            <meta http-equiv="x-ua-compatible" content="IE=edge,chrome=1"/>
            <meta name="description" content=""/>
            <meta name="viewport"
                  content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0"/>
            <link rel="icon"
                  type="image/x-icon"
                  href="{% static 'core/images/favicon.ico' %}"/>
            {% block extra_head %}
            {% endblock extra_head %}
            <link href="https://fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,500,500i,700,700i,900"
                  rel="stylesheet"/>
            <!-- Bootstrap 5 -->
            <link rel="stylesheet"
                  href="{% static 'core/vendor/css/bootstrap5.min.css' %}"/>
            <!-- Icon fonts -->
            <link rel="stylesheet"
                  href="{% static 'core/vendor/fonts/fontawesome.css' %}"/>
            <link rel="stylesheet" href="{% static 'core/vendor/fonts/ionicons.css' %}"/>
            <link rel="stylesheet"
                  href="{% static 'core/vendor/fonts/linearicons.css' %}"/>
            <link rel="stylesheet"
                  href="{% static 'core/vendor/fonts/open-iconic.css' %}"/>
            <link rel="stylesheet"
                  href="{% static 'core/vendor/fonts/pe-icon-7-stroke.css' %}"/>
            <link rel="stylesheet"
                  href="{% static 'core/vendor/css/rtl/bootstrap.css' %}"
                  class="theme-settings-bootstrap-css"/>
            <link rel="stylesheet"
                  href="{% static 'core/vendor/css/rtl/appwork.css' %}"
                  class="theme-settings-appwork-css"/>
            <link rel="stylesheet"
                  href="{% static 'core/vendor/css/rtl/theme-corporate.css' %}"
                  class="theme-settings-theme-css"/>
            <link rel="stylesheet"
                  href="{% static 'core/vendor/css/rtl/colors.css' %}"
                  class="theme-settings-colors-css"/>
            <link rel="stylesheet" href="{% static 'core/vendor/css/rtl/uikit.css' %}"/>
            <!-- Design System do Governo Federal -->
            <!-- Fonte Rawline-->
            <link rel="stylesheet"
                  href="https://cdn.dsgovserprodesign.estaleiro.serpro.gov.br/design-system/fonts/rawline/css/rawline.css"/>
            <!-- Fonte Raleway-->
            <link rel="stylesheet"
                  href="https://fonts.googleapis.com/css?family=Raleway:300,400,500,600,700,800,900&amp;display=swap"/>
            <!-- Design System de Governo-->
            <link rel="stylesheet" href="{% static 'core/css/dsgov.min.css' %}" />
            <!-- Fontawesome-->
            <link rel="stylesheet"
                  href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css"/>
            <!-- Custom CSS -->
            <link rel="stylesheet" href="{% static 'core/css/custom.css' %}"/>
            <!-- JQuery -->
            <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
            <!-- Google Analytics -->
            <script>
        (function (i, s, o, g, r, a, m) {
            i['GoogleAnalyticsObject'] = r;
            i[r] = i[r] || function () {
                (i[r].q = i[r].q || []).push(arguments)
            }, i[r].l = 1 * new Date();
            a = s.createElement(o),
                m = s.getElementsByTagName(o)[0];
            a.async = 1;
            a.src = g;
            m.parentNode.insertBefore(a, m)
        })(window, document, 'script', 'https://www.google-analytics.com/analytics.js', 'ga');
        ga('create', 'UA-47831155-1', 'auto');
        ga('send', 'pageview');
            </script>
            <!-- Fim do Google Analytics -->
            {% block extra_css %}
            {% endblock extra_css %}
      </head>
      <body>
            <div class="layout-wrapper layout-2">
                  <div class="layout-inner">
                        <div class="layout-container">
                              {% include "./block/header_menu.html" %}
                              <div class="layout-content">
                                    <div class="container flex-grow-1 container-p-y">
                                          {% include "./block/bread_cumbs.html" %}
                                          {% block content %}
                                          {% endblock content %}
                                    </div>
                                    <nav class="layout-footer footer bg-footer-theme">
                                          {% include "./block/footer.html" %}
                                    </nav>
                              </div>
                        </div>
                  </div>
            </div>
            <script src="{% static 'core/vendor/js/material-ripple.js' %}"></script>
            <script src="{% static 'core/vendor/js/layout-helpers.js' %}"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
            <!-- Remover Alert -->
            <script src="{% static 'core/js/notificacao.js' %}"></script>
            <!-- Core scripts -->
            <script src="{% static 'core/vendor/js/pace.js' %}"></script>
            <!-- Core scripts -->
            <script src="{% static 'core/vendor/libs/popper/popper.js' %}"></script>
            <script src="{% static 'core/vendor/js/bootstrap.js' %}"></script>
            <script src="{% static 'core/vendor/js/sidenav.js' %}"></script>
            <!-- Input Mask Plugin -->
            <script src="{% static 'core/plugins/input-mask/js/jquery.mask.min.js' %}"></script>
            <script src="{% static 'core/plugins/input-mask/plugin.js' %}"></script>
            <!-- Demo -->
            <script src="{% static 'core/js/demo.js' %}"></script>
            <script src="{% static 'core/js/core.js' %}"></script>
            <script src="{% static 'core/js/jquery.formset.js' %}"></script>
            <script src="{% static 'core/js/inline.js' %}"></script>
            <!-- Design System do Governo Federal -->
            <script src="{% static 'core/js/dsgov-init.js' %}"></script>
            <!-- Bootstrap 5 -->
            <script src="{% static 'core/vendor/js/bootstrap5.min.js' %}"></script>
            {% block extra_js %}
            {% endblock extra_js %}
      </body>
</html>

core/templates/core/base_menu_vertical.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-BR" dir="ltr">

<head>
    <meta charset="utf-8">
    <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta http-equiv="Content-Language" content="en" />
    <meta name="msapplication-TileColor" content="#2d89ef">
    <meta name="theme-color" content="#4188c9">
    <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <link rel="icon" href="./favicon.ico" type="image/x-icon" />
    <link rel="shortcut icon" type="image/x-icon" href="./favicon.ico" />
    <title>{% block title %}{% endblock title %}</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,300i,400,400i,500,500i,600,600i,700,700i&amp;subset=latin-ext">
    <script src="{% static 'core/js/vendors/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'core/js/core.js' %}"></script>
    <script src="{% static 'core/js/vendors/jquery-jvectormap-2.0.3.min.js' %}"></script>
    <script src="{% static 'core/js/vendors/jquery-jvectormap-de-merc.js' %}"></script>
    <script src="{% static 'core/js/vendors/jquery-jvectormap-world-mill.js' %}"></script>
    <script src="{% static 'core/js/vendors/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'core/js/vendors/jquery.tablesorter.min.js' %}"></script>
    <script src="{% static 'core/js/vendors/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'core/js/vendors/chart.bundle.min.js' %}"></script>
    <script src="{% static 'core/js/vendors/selectize.min.js' %}"></script>
    <!-- <script src="{% static 'core/js/vendors/circle-progress.min.js' %}"></script> -->

    <!-- Dashboard Core -->
    <link href="{% static 'core/css/dashboard.css' %}" rel="stylesheet" />
    <script src="{% static 'core/js/dashboard.js' %}"></script>
    <!-- c3.js Charts Plugin -->
    <script src="{% static 'core/plugins/charts-c3/js/d3.v3.min.js' %}"></script>
    <script src="{% static 'core/plugins/charts-c3/js/c3.min.js' %}"></script>
    <link href="{% static 'core/plugins/charts-c3/plugin.css' %}" rel="stylesheet" />
    <script src="{% static 'core/plugins/charts-c3/plugin.js' %}"></script>
    <!-- Google Maps Plugin -->
    <link href="{% static 'core/plugins/maps-google/plugin.css' %}" rel="stylesheet" />
    <script src="{% static 'core/plugins/maps-google/plugin.js' %}"></script>
    <!-- Input Mask Plugin -->
    <script src="{% static 'core/plugins/input-mask/js/jquery.mask.min.js' %}"></script>
    <script src="{% static 'core/plugins/input-mask/plugin.js' %}"></script>

    <script src="{% static 'core/plugins//prismjs/js/prism.pack.js' %}"></script>

    <!-- Jquery Admin Django -->
    <script src="{% static 'core/js/jquery.formset.js' %}"></script>
    <script src="{% static 'core/js/inline.js' %}"></script>

    {% block extra_css %}{% endblock extra_css %}
    {% block extra_head %}{% endblock extra_head %}
</head>

<body class="">
    <div class="page">
        <div class="page-main">
            <!-- Show only user is logged -->
            {% if user.is_authenticated %}
            <div class="header py-4">
                <div class="container-fluid px-5">
                    <div class="d-flex">
                        <a class="header-brand" href="/core">
                            {{ system_name }}
                        </a>
                        <div class="d-flex order-lg-2 ml-auto">
                            <div class="nav-item d-none d-md-flex">

                            </div>
                            <div class="dropdown">
                                <a href="#" class="nav-link pr-0 leading-none" data-toggle="dropdown">
                                    <!--                                    <span class="avatar" style="background-image: url(./demo/faces/female/25.jpg)"></span>-->
                                    <span class="ml-2 d-none d-lg-block">
                                        <span class="text-default">{{ user.username|title }}</span>
                                        <small class="text-muted d-block mt-1">{{ user.email }}</small>
                                    </span>
                                </a>
                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                    <a class="dropdown-item" href="{% url 'core:profile' %}">
                                        <i class="dropdown-icon fe fe-user"></i> Perfil
                                    </a>
                                    <a class="dropdown-item" href="{% url 'core:settings' %}">
                                        <i class="dropdown-icon fe fe-settings"></i> Settings
                                    </a>
                                    <a class="dropdown-item" href="#">
                                        <span class="float-right"><span class="badge badge-primary">6</span></span>
                                        <i class="dropdown-icon fe fe-mail"></i> Inbox
                                    </a>
                                    <a class="dropdown-item" href="#">
                                        <i class="dropdown-icon fe fe-send"></i> Message
                                    </a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">
                                        <i class="dropdown-icon fe fe-help-circle"></i> Need help?
                                    </a>
                                    <a class="dropdown-item" href="{% url 'core:logout' %}">
                                        <i class="dropdown-icon fe fe-log-out"></i> Logout
                                    </a>
                                </div>
                            </div>
                        </div>
                        <a href="#" class="header-toggler d-lg-none ml-3 ml-lg-0" data-toggle="collapse"
                            data-target="#headerMenuCollapse">
                            <span class="header-toggler-icon"></span>
                        </a>
                    </div>
                </div>
            </div>
            {% endif %}
            <!-- end block show only user is logged -->
            <div id="div_menu_and_content" class="row m-0 p-0">
                <div class="m-0 pl-0 mh-100 h-100">
                    {% include './block/vertical_menu.html' %}
                </div>
                <div id="div_block_content" class="col-10 p-5 mw-100 mh-100">
                    {% block content %} {% endblock content %}
                </div>
            </div>
        </div>
        <footer class="footer">
            <div class="container">
                <div class="row align-items-center flex-row-reverse">
                    <div class="col-auto ml-lg-auto">
                        <div class="row align-items-center">
                            {% if user.last_login %}
                            Sessão iniciada: {{ user.last_login }}
                            | {{ user_ip }}
                            {% endif %}
                        </div>
                    </div>
                    <div class="col-12 col-lg-auto mt-3 mt-lg-0 text-center">
                        Copyright © 2018
                    </div>
                </div>
            </div>
        </footer>
    </div>
    {% block extra_js %}{% endblock extra_js %}
    <script>
        function applySideBarState() {
            $('#sidebar_left').addClass(window.localStorage.getItem("sidebar_active"));
        }

        function applyInitialTheme() {
            const theme = window.localStorage.getItem("site-theme")
            if (theme !== null) {
                const htmlTag = document.getElementsByTagName("html")[0]
                htmlTag.setAttribute("data-theme", theme)
            }
        }

        applyInitialTheme();
        applySideBarState();
    </script>
</body>

</html>

core/templates/core/index_app.html
{% extends 'core/base.html' %} {% block content %}
<div id="content_index_page_app" class="row mb-4 content-page h-100">
    <div id="submenu_index_page" class="col-3 col-xl-2 h-100">
        <!-- Menu lateral com os models das app -->
        <div class="card menu-vertical-app h-100">
            <div class="card-header">
                <h3 class="card-title"><strong>{% block title_modulo %}{% endblock title_modulo %}</strong></h3>
            </div>
            <!-- <div class="card-body"> -->
            <table class="table table-borderless table-hover table-sm">
                <tbody>
                    {% block menu_app %}
                    {% endblock menu_app %}
                </tbody>
            </table>
            <!-- </div> -->
        </div>
    </div>
    <div id="content_index_page" class="col-9 col-xl-10"></div>
</div>
{% endblock content %}