base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from drf_yasg import openapi
from drf_yasg.views import get_schema_view
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

from core.views.base import BaseIndexTemplate

from . import urls_api

schema_view = get_schema_view(
    openapi.Info(
        title="E-Collect API",
        default_version="v1",
        description="Swagger do Projeto E-Collect API",
        terms_of_service="https://www.rede.ulbra.br/",
        contact=openapi.Contact(email="marcomartins06@rede.ulbra.br"),
        license=openapi.License(name="BSD License"),
    ),
    url="http://127.0.0.1:8000" if settings.DEBUG else "https://www.rede.ulbra.br",
    public=True,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", BaseIndexTemplate.as_view(), name="index"),
    path("core/", include("core.urls", namespace="core")),
    path("core/", include("usuario.urls", namespace="usuario")),
    path("core/", include("configuracao_agtec_core.urls", namespace="configuracao_agtec_core")),
    # Urls do Swagger
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    # Url de autenticação do DRF
    path("auth/", include("dj_rest_auth.urls")),
    # URL de autenticação JWT
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
]

# Adicionando as urls da APIRest no urlpatterns do projeto
urlpatterns += urls_api.urlpatterns

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]

configuracao_agtec_core/urls.py
from django.urls import path

from .views import (
    Configuracao_Agtec_CoreIndexTemplateView,
    DadosGeraisCreateView,
    DadosGeraisDeleteView,
    DadosGeraisDetailView,
    DadosGeraisListView,
    DadosGeraisRestoreView,
    DadosGeraisUpdateView,
    GestorCreateView,
    GestorDeleteView,
    GestorDetailView,
    GestorListView,
    GestorRestoreView,
    GestorUpdateView,
    ImagemLoginCreateView,
    ImagemLoginDeleteView,
    ImagemLoginDetailView,
    ImagemLoginListView,
    ImagemLoginRestoreView,
    ImagemLoginUpdateView,
    LogoSistemaCreateView,
    LogoSistemaDeleteView,
    LogoSistemaDetailView,
    LogoSistemaListView,
    LogoSistemaRestoreView,
    LogoSistemaUpdateView,
)

app_name = "configuracao_agtec_core"

# URLs do Models Gestor
urlpatterns = [
    path(
        "configuracao_agtec_core/",
        Configuracao_Agtec_CoreIndexTemplateView.as_view(),
        name="configuracao_agtec_core-index",
    ),
    path("configuracao_agtec_core/gestor/", GestorListView.as_view(), name="gestor-list"),
    path("configuracao_agtec_core/gestor/create/", GestorCreateView.as_view(), name="gestor-create"),
    path("configuracao_agtec_core/gestor/<uuid:pk>/", GestorDetailView.as_view(), name="gestor-detail"),
    path("configuracao_agtec_core/gestor/update/<uuid:pk>/", GestorUpdateView.as_view(), name="gestor-update"),
    path("configuracao_agtec_core/gestor/delete/<uuid:pk>/", GestorDeleteView.as_view(), name="gestor-delete"),
    path("configuracao_agtec_core/gestor/restore/<uuid:pk>/", GestorRestoreView.as_view(), name="gestor-restore"),
]


# URLs do Models ImagemLogin
urlpatterns += [
    path(
        "configuracao_agtec_core/",
        Configuracao_Agtec_CoreIndexTemplateView.as_view(),
        name="configuracao_agtec_core-index",
    ),
    path("configuracao_agtec_core/imagemlogin/", ImagemLoginListView.as_view(), name="imagemlogin-list"),
    path("configuracao_agtec_core/imagemlogin/create/", ImagemLoginCreateView.as_view(), name="imagemlogin-create"),
    path("configuracao_agtec_core/imagemlogin/<uuid:pk>/", ImagemLoginDetailView.as_view(), name="imagemlogin-detail"),
    path(
        "configuracao_agtec_core/imagemlogin/update/<uuid:pk>/",
        ImagemLoginUpdateView.as_view(),
        name="imagemlogin-update",
    ),
    path(
        "configuracao_agtec_core/imagemlogin/delete/<uuid:pk>/",
        ImagemLoginDeleteView.as_view(),
        name="imagemlogin-delete",
    ),
    path(
        "configuracao_agtec_core/imagemlogin/restore/<uuid:pk>/",
        ImagemLoginRestoreView.as_view(),
        name="imagemlogin-restore",
    ),
]


# URLs do Models LogoSistema
urlpatterns += [
    path(
        "configuracao_agtec_core/",
        Configuracao_Agtec_CoreIndexTemplateView.as_view(),
        name="configuracao_agtec_core-index",
    ),
    path("configuracao_agtec_core/logosistema/", LogoSistemaListView.as_view(), name="logosistema-list"),
    path("configuracao_agtec_core/logosistema/create/", LogoSistemaCreateView.as_view(), name="logosistema-create"),
    path("configuracao_agtec_core/logosistema/<uuid:pk>/", LogoSistemaDetailView.as_view(), name="logosistema-detail"),
    path(
        "configuracao_agtec_core/logosistema/update/<uuid:pk>/",
        LogoSistemaUpdateView.as_view(),
        name="logosistema-update",
    ),
    path(
        "configuracao_agtec_core/logosistema/delete/<uuid:pk>/",
        LogoSistemaDeleteView.as_view(),
        name="logosistema-delete",
    ),
    path(
        "configuracao_agtec_core/logosistema/restore/<uuid:pk>/",
        LogoSistemaRestoreView.as_view(),
        name="logosistema-restore",
    ),
]


# URLs do Models DadosGerais
urlpatterns += [
    path(
        "configuracao_agtec_core/",
        Configuracao_Agtec_CoreIndexTemplateView.as_view(),
        name="configuracao_agtec_core-index",
    ),
    path("configuracao_agtec_core/dadosgerais/", DadosGeraisListView.as_view(), name="dadosgerais-list"),
    path("configuracao_agtec_core/dadosgerais/create/", DadosGeraisCreateView.as_view(), name="dadosgerais-create"),
    path("configuracao_agtec_core/dadosgerais/<uuid:pk>/", DadosGeraisDetailView.as_view(), name="dadosgerais-detail"),
    path(
        "configuracao_agtec_core/dadosgerais/update/<uuid:pk>/",
        DadosGeraisUpdateView.as_view(),
        name="dadosgerais-update",
    ),
    path(
        "configuracao_agtec_core/dadosgerais/delete/<uuid:pk>/",
        DadosGeraisDeleteView.as_view(),
        name="dadosgerais-delete",
    ),
    path(
        "configuracao_agtec_core/dadosgerais/restore/<uuid:pk>/",
        DadosGeraisRestoreView.as_view(),
        name="dadosgerais-restore",
    ),
]

configuracao_agtec_core/models.py
from django.db import models

from core.models import Base


class Gestor(Base):
    nome = models.CharField("Nome", max_length=100)
    email = models.EmailField("E-mail")
    funcao = models.CharField("Função", max_length=100)
    telefone = models.CharField("Telefone", max_length=11)
    assinatura = models.ImageField("Assinatura", upload_to="assinaturas", blank=True, null=True)

    def __str__(self):
        return f"{self.nome} - {self.funcao}"

    class Meta:
        verbose_name = "Gestor"
        verbose_name_plural = "Gestores"
        fields_display = ["nome", "email", "funcao", "telefone", "assinatura"]
        icon_model = "fa fa-user"
        db_table = "configuracao_gestor"


class ImagemLogin(Base):
    imagem = models.ImageField("Imagem de login", upload_to="imagens_login")
    ativo = models.BooleanField("Ativo", default=True)
    login_usuario = models.BooleanField("Login de Usuário?", default=False)

    def __str__(self):
        return str(self.imagem)

    class Meta:
        verbose_name = "Imagem de Login"
        verbose_name_plural = "Imagens de Login"
        fields_display = ["imagem", "ativo"]
        icon_model = "fa fa-image"
        db_table = "configuracao_imagem_login"


class LogoSistema(Base):
    imagem = models.ImageField("Logo do Sistema", upload_to="logos")
    ativo = models.BooleanField("Ativo", default=True)

    def __str__(self):
        return str(self.imagem)

    class Meta:
        verbose_name = "Logo do Sistema"
        verbose_name_plural = "Logos do Sistema"
        fields_display = ["imagem", "ativo"]
        icon_model = "fa fa-image"
        db_table = "configuracao_logo_sistema"


class DadosGerais(Base):
    telefone = models.CharField("Telefone", max_length=11)
    endereco = models.CharField("Endereço", max_length=100)
    horario_atendimento = models.CharField("Horário de atendimento", max_length=100)

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name = "Dados Gerais"
        verbose_name_plural = "Dados Gerais"
        fields_display = ["telefone", "endereco", "horario_atendimento"]
        icon_model = "fa fa-info"
        db_table = "configuracao_dados_gerais"

configuracao_agtec_core/forms.py
from django import forms

from core.forms import BaseForm
from core.utils import somente_numeros

from .models import DadosGerais, Gestor, ImagemLogin, LogoSistema


class GestorForm(BaseForm):
    """Form padrão para o model Gestor"""

    telefone = forms.CharField(
        widget=forms.TextInput(attrs={"data-mask": "(99) 99999-9999", "placeholder": "(99) 99999-9999"}),
    )

    def clean_telefone(self):
        self.cleaned_data["telefone"] = somente_numeros(self.cleaned_data["telefone"])
        if len(self.cleaned_data["telefone"]) not in {11, 10}:
            raise forms.ValidationError("Telefone inválido")
        return self.cleaned_data["telefone"]

    class Meta:
        exclude = ["deleted", "enabled"]
        model = Gestor


class DadosGeraisForm(BaseForm):
    """Form padrão para o model DadosGerais"""

    telefone = forms.CharField(
        widget=forms.TextInput(attrs={"data-mask": "(99) 99999-9999", "placeholder": "(99) 99999-9999"}),
    )

    horario_atendimento = forms.CharField(
        label="Horário de atendimento",
        widget=forms.TextInput(
            attrs={
                "placeholder": "08:00 às 18:00",
            }
        ),
    )

    def clean_telefone(self):
        self.cleaned_data["telefone"] = somente_numeros(self.cleaned_data["telefone"])
        if len(self.cleaned_data["telefone"]) not in {11, 10}:
            raise forms.ValidationError("Telefone inválido")
        return self.cleaned_data["telefone"]

    def clean(self):
        if DadosGerais.objects.exists():
            raise forms.ValidationError("Já existe uma configuração cadastrada")

    class Meta:
        exclude = ["deleted", "enabled"]
        model = DadosGerais


class ImagemLoginForm(BaseForm):
    """Form padrão para o model ImagemLogin"""

    class Meta:
        exclude = ["deleted", "enabled"]
        model = ImagemLogin


class LogoSistemaForm(BaseForm):
    """Form padrão para o model LogoSistema"""

    class Meta:
        exclude = ["deleted", "enabled"]
        model = LogoSistema

configuracao_agtec_core/views/dadosgerais.py
from configuracao_agtec_core.forms import DadosGeraisForm
from configuracao_agtec_core.models import DadosGerais
from core.views.base import (
    BaseCreateView,
    BaseDeleteView,
    BaseDetailView,
    BaseListView,
    BaseRestoreView,
    BaseUpdateView,
)


# Views do Models DadosGerais
class DadosGeraisListView(BaseListView):
    """Classe para gerenciar a listagem do DadosGerais"""

    model = DadosGerais
    template_name = "configuracao_agtec_core/dadosgerais/dadosgerais_list.html"
    context_object_name = "dadosgerais"
    list_display = ["telefone", "endereco", "horario_atendimento"]
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(DadosGeraisListView, self).get_context_data(**kwargs)
        return context

    def get_queryset(self):
        """Subscrevendo o queryset para
        filtrar os dados conforme o perfil logado

        Returns:
            QuerySet
        """

        if self.request.user.is_superuser:
            queryset = super(DadosGeraisListView, self).get_queryset()
            return queryset
        else:
            queryset = super(DadosGeraisListView, self).get_queryset()
            return queryset


class DadosGeraisDetailView(BaseDetailView):
    """Classe para gerenciar o detalhe do DadosGerais"""

    model = DadosGerais
    form_class = DadosGeraisForm
    success_url = "configuracao_agtec_core:dadosgerais-list"
    template_name = "configuracao_agtec_core/dadosgerais/dadosgerais_detail.html"
    context_object_name = "dadosgerais"

    def get_context_data(self, **kwargs):
        context = super(DadosGeraisDetailView, self).get_context_data(**kwargs)
        return context


class DadosGeraisCreateView(BaseCreateView):
    """Classe para gerenciar o create do DadosGerais"""

    model = DadosGerais
    form_class = DadosGeraisForm
    context_object_name = "dadosgerais"
    success_url = "configuracao_agtec_core:dadosgerais-list"
    template_name = "configuracao_agtec_core/dadosgerais/dadosgerais_create.html"
    # inlines = []


class DadosGeraisUpdateView(BaseUpdateView):
    """Classe para gerenciar a update do DadosGerais"""

    model = DadosGerais
    form_class = DadosGeraisForm
    context_object_name = "dadosgerais"
    success_url = "configuracao_agtec_core:dadosgerais-list"
    template_name = "configuracao_agtec_core/dadosgerais/dadosgerais_update.html"
    # inlines = []


class DadosGeraisDeleteView(BaseDeleteView):
    """Classe para gerenciar o delete do DadosGerais"""

    model = DadosGerais
    form_class = DadosGeraisForm
    context_object_name = "dadosgerais"
    success_url = "configuracao_agtec_core:dadosgerais-list"
    template_name = "configuracao_agtec_core/dadosgerais/dadosgerais_delete.html"


class DadosGeraisRestoreView(BaseRestoreView):
    """Classe para gerenciar o restore do DadosGerais"""

    model = DadosGerais
    context_object_name = "dadosgerais"
    success_url = "configuracao_agtec_core:dadosgerais-list"
    template_name = "configuracao_agtec_core/dadosgerais/dadosgerais_restore.html"


# Fim das Views do Models DadosGerais

configuracao_agtec_core/views/gestor.py
from configuracao_agtec_core.forms import GestorForm
from configuracao_agtec_core.models import Gestor
from core.views.base import (
    BaseCreateView,
    BaseDeleteView,
    BaseDetailView,
    BaseListView,
    BaseRestoreView,
    BaseUpdateView,
)


# Views do Models Gestor
class GestorListView(BaseListView):
    """Classe para gerenciar a listagem do Gestor"""

    model = Gestor
    template_name = "configuracao_agtec_core/gestor/gestor_list.html"
    context_object_name = "gestor"
    list_display = ["nome", "email", "funcao", "telefone", "assinatura"]
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super(GestorListView, self).get_context_data(**kwargs)
        return context

    def get_queryset(self):
        """Subscrevendo o queryset para
        filtrar os dados conforme o perfil logado

        Returns:
            QuerySet
        """

        if self.request.user.is_superuser:
            queryset = super(GestorListView, self).get_queryset()
            return queryset
        else:
            queryset = super(GestorListView, self).get_queryset()
            return queryset


class GestorDetailView(BaseDetailView):
    """Classe para gerenciar o detalhe do Gestor"""

    model = Gestor
    form_class = GestorForm
    success_url = "configuracao_agtec_core:gestor-list"
    template_name = "configuracao_agtec_core/gestor/gestor_detail.html"
    context_object_name = "gestor"

    def get_context_data(self, **kwargs):
        context = super(GestorDetailView, self).get_context_data(**kwargs)
        return context


class GestorCreateView(BaseCreateView):
    """Classe para gerenciar o create do Gestor"""

    model = Gestor
    form_class = GestorForm
    context_object_name = "gestor"
    success_url = "configuracao_agtec_core:gestor-list"
    template_name = "configuracao_agtec_core/gestor/gestor_create.html"
    # inlines = []


class GestorUpdateView(BaseUpdateView):
    """Classe para gerenciar a update do Gestor"""

    model = Gestor
    form_class = GestorForm
    context_object_name = "gestor"
    success_url = "configuracao_agtec_core:gestor-list"
    template_name = "configuracao_agtec_core/gestor/gestor_update.html"
    # inlines = []


class GestorDeleteView(BaseDeleteView):
    """Classe para gerenciar o delete do Gestor"""

    model = Gestor
    form_class = GestorForm
    context_object_name = "gestor"
    success_url = "configuracao_agtec_core:gestor-list"
    template_name = "configuracao_agtec_core/gestor/gestor_delete.html"


class GestorRestoreView(BaseRestoreView):
    """Classe para gerenciar o restore do Gestor"""

    model = Gestor
    context_object_name = "gestor"
    success_url = "configuracao_agtec_core:gestor-list"
    template_name = "configuracao_agtec_core/gestor/gestor_restore.html"


# Fim das Views do Models Gestor

configuracao_agtec_core/views/index.py
from core.views.base import BaseTemplateView


# Views Inicial Configuracao_Agtec_Core
class Configuracao_Agtec_CoreIndexTemplateView(BaseTemplateView):
    # Views para renderizar a tela inicial Configuracao_Agtec_Core
    template_name = "configuracao_agtec_core/index.html"
    context_object_name = "configuracao_agtec_core"

    def get_context_data(self, **kwargs):
        context = super(Configuracao_Agtec_CoreIndexTemplateView, self).get_context_data(**kwargs)
        return context

configuracao_agtec_core/templates/configuracao_agtec_core/dadosgerais/dadosgerais_delete.html
<!--
Arquivo gerado automaticamente pelo build.
Caso deseje bloquear o parser nesse arquivo, basta adicionar o caracter #(cerquilha) antes da palavra a seguir
#FileLocked
-->
{% extends "core/index_delete.html" %}
{% load base %}
{% block title %}
    Deletar Configuração
{% endblock title %}
{% block title_modulo %}
    Configuração
{% endblock title_modulo %}
{% block titledelete_app %}
    <h3 class="m-4">Apagar: {{ object }} ?</h3>
{% endblock titledelete_app %}
{% block delete_app %}
    <form class="needs-validation was-validated flex-buttons-end gap-small"
          method="post"
          novalidate>
        {% csrf_token %}
        <div>
            <a href="{% url 'configuracao_agtec_core:dadosgerais-list' %}"
               class="br-button block">Cancelar</a>
        </div>
        <div>
            <input type="submit" class="br-button danger block" value="Excluir" />
        </div>
    </form>
{% endblock delete_app %}

configuracao_agtec_core/templates/configuracao_agtec_core/dadosgerais/dadosgerais_detail.html
{% extends "core/index_detail.html" %}
{% load static %}
{% load base %}
<!--
Arquivo gerado automaticamente pelo build.
Caso deseje bloquear o parser nesse arquivo, basta adicionar o caracter #(cerquilha) antes da palavra a seguir
#FileLocked
-->
{% block title %}
    Detalhes de Configuração
{% endblock title %}
<span class="text-muted font-weight-light"></span>
{% block title_modulo %}
    <h4 class="font-weight-bold py-3 mb-4">
        <span class="text-muted font-weight-light">Configuração /</span> Detalhes {{ model_name }}
    </h4>
{% endblock title_modulo %}
<div class="row">
    {% block menu_app %}
        {% for app in apps %}
            {% if app.real_name_app.lower == 'configuracao_agtec_core' %}
                {% for model in app.models_app %}
                    {% if model|has_view_permission:request %}
                        <div class="col-xl-12">
                            <i class="ion ion-md-arrow-dropight text-muted"></i> &nbsp;
                            <a href="{% url model.path_url %}">{{ model.name_model|title }}</a>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        {% endfor %}
    {% endblock menu_app %}
    {% block detail %}
        <div class="col-xl-12">
            <div class="br-list" role="list">
                {% for field in object_list %}
                    <div class="col-xl-6">
                        <h4 class="align-items-center my-4">{{ field.0|capfirst }}</h4>
                        <p>{{ field.1 }}</p>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="card-footer flex-buttons-end gap-small">
            <div>
                <a class="br-button block"
                   href="{% url 'configuracao_agtec_core:dadosgerais-list' %}">Voltar</a>
            </div>
            {% if perms.core.view_audit and audit %}
                <div>
                    <a href="{% url url_detail object.pk %}audit"
                       class="br-button secondary block">Auditar</a>
                </div>
            {% endif %}
        </div>
    {% endblock detail %}
</div>

configuracao_agtec_core/templates/configuracao_agtec_core/dadosgerais/dadosgerais_list.html
<!--
Arquivo gerado automaticamente pelo build.
Caso deseje bloquear o parser nesse arquivo, basta adicionar o caracter #(cerquilha) antes da palavra a seguir
FileLocked
-->
{% extends "core/index_list.html" %}
{% load base %}
{% block title %}
    Listagem Configuração
{% endblock title %}
{% block title_modulo %}
    <h4 class="font-weight-bold m-1">Configuração - {{ model_name }}</h4>
{% endblock title_modulo %}
<!-- Bloco para passagem da URL do formulário de cadastro -->
{% block uriadd %}
    {% url "configuracao_agtec_core:dadosgerais-create" %}
{% endblock uriadd %}
{% block list_app %}
    <table>
        <thead>
            <tr>
                <th class="table-actions" scope="col">Ações</th>
                <th></th>
                <!--REPLACE_THEAD-->
                <th scope="col" class="table-delete"></th>
            </tr>
        </thead>
        <tbody>
            {% for item in dadosgerais %}
                <tr {% if item.deleted %}class="deleted"{% endif %}>
                    <td class="text-center">
                        {% if perms.configuracao_agtec_core.view_dadosgerais %}
                            <a href="{% url 'configuracao_agtec_core:dadosgerais-detail' item.pk %}"
                               class="br-button circle primary small m-1"
                               data-toggle="tooltip"
                               data-placement="bottom"
                               title="Visualizar">
                                <i class="fas fa-eye fa-sm"></i>
                            </a>
                        {% endif %}
                        {% if perms.configuracao_agtec_core.change_dadosgerais %}
                            <a href="{% url 'configuracao_agtec_core:dadosgerais-update' item.pk %}"
                               class="br-button secondary circle small m-1"
                               data-toggle="tooltip"
                               data-placement="bottom"
                               title="Editar">
                                <i class="fas fa-pencil-alt fa-sm"></i>
                            </a>
                        {% endif %}
                    </td>
                    <td></td>
                    <!--REPLACE_TLINE-->
                    <td class="text-center">
                        {% if perms.configuracao_agtec_core.delete_dadosgerais %}
                            {% if item.deleted %}
                                <a href="{% url 'configuracao_agtec_core:dadosgerais-restore' item.pk %}"
                                   class="br-button circle small text-success"
                                   data-toggle="tooltip"
                                   data-placement="bottom"
                                   title="Restaurar">
                                    <i class="fas fa-trash-restore fa-sm"></i>
                                </a>
                            {% else %}
                                <a href="{% url 'configuracao_agtec_core:dadosgerais-delete' item.pk %}"
                                   class="br-button circle small text-danger"
                                   data-toggle="tooltip"
                                   data-placement="bottom"
                                   title="Excluir">
                                    <i class="fas fa-trash fa-sm"></i>
                                </a>
                            {% endif %}
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock list_app %}
{% block size_itens %}
    Exibindo {{ dadosgerais.count }} de {{ paginator.count }} itens encontrados.
{% endblock size_itens %}

configuracao_agtec_core/templates/configuracao_agtec_core/dadosgerais/dadosgerais_restore.html
<!--
Arquivo gerado automaticamente pelo build.
Caso deseje bloquear o parser nesse arquivo, basta adicionar o caracter #(cerquilha) antes da palavra a seguir
#FileLocked
-->
{% extends "core/index_restore.html" %}
{% load base %}
{% block title %}
    Restaurar Configuração
{% endblock title %}
{% block title_modulo %}
    Configuração
{% endblock title_modulo %}
{% block titlerestore_app %}
    <h3 class="m-4">Restaurar: {{ object }} ?</h3>
{% endblock titlerestore_app %}
{% block restore_app %}
    <form class="needs-validation was-validated flex-buttons-end gap-small"
          method="post"
          novalidate>
        {% csrf_token %}
        <div>
            <a href="{% url 'configuracao_agtec_core:dadosgerais-list' %}"
               class="br-button block">Cancelar</a>
        </div>
        <div>
            <input type="submit" class="br-button block primary" value="Restaurar">
        </div>
    </form>
{% endblock restore_app %}